# Generated by Django to establish the api app's initial schema.
# This restores the missing parent migration for api.0002.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=255)),
                ('device_code', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reading_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ph_value', models.FloatField()),
                ('turbidity_value', models.FloatField()),
                ('tds_value', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('ec_value', models.FloatField()),
                ('is_alert', models.BooleanField(default=False)),
                ('alert_reason', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'db_table': 'sensor_readings',
                'ordering': ['-reading_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('threshold_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=50)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
            options={
                'verbose_name': 'Threshold',
                'verbose_name_plural': 'Thresholds',
                'db_table': 'thresholds',
                'unique_together': {('device', 'sensor_type')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=100)),
                ('alert_message', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensorreading')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
