# Generated by Django 5.2.4 on 2026-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_arduino_mac_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='idx_alert_status'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', '-created_at'], name='idx_alert_device_created'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', '-reading_timestamp'], name='idx_reading_device_ts'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['-reading_timestamp'], name='idx_reading_ts'),
        ),
    ]
